# utiliza a imagem do node
image: node:16.0.0
# definições
definitions:
  # persiste o npm
  caches:
    npm: ~/.npm
# define os pipelines
pipelines:
  # define qual branch deve rodar 
  branches:
    # executa o script apenas no master
    master:
      # executa o build
      - step:
          # nome do passo
          name: (PRD) Construindo e publicando imagem
          # serviços adicionais
          services:
            - docker
          # scripts que são executados
          script:
            - sed -i "s/pasta_build/production/g" ./vue.config.js
            - npm install --g yarn --force
            - yarn
            - npm run build
            - npm run deploy
    # executa o script apenas no master
    develop:
      # executa o build
      - step:
          # nome do passo
          name: (QA) Construindo e publicando imagem
          # serviços adicionais deploy
          services:
            - docker
          # scripts que são executados
          script:
            - sed -i "s/pasta_build/qa/g" ./vue.config.js
            - npm install --g yarn --force
            - yarn
            - npm run build-test
            - npm run deploy